# Generated by Django 5.2.5 on 2026-03-19 06:54
"""Добавление translation-полей в state (колонки уже существуют в БД) + переименование индекса."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='emaillog',
                    new_name='orders_emai_status_5626e6_idx',
                    old_name='orders_emai_status_12a3c6_idx',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='emailtemplate',
                    name='body_en',
                    field=models.TextField(help_text='Плейн-текст. Плейсхолдеры: {user_name}, {verify_url}, {order_number} и т.д.', null=True, verbose_name='Текст письма'),
                ),
                migrations.AddField(
                    model_name='emailtemplate',
                    name='body_kk',
                    field=models.TextField(help_text='Плейн-текст. Плейсхолдеры: {user_name}, {verify_url}, {order_number} и т.д.', null=True, verbose_name='Текст письма'),
                ),
                migrations.AddField(
                    model_name='emailtemplate',
                    name='body_ru',
                    field=models.TextField(help_text='Плейн-текст. Плейсхолдеры: {user_name}, {verify_url}, {order_number} и т.д.', null=True, verbose_name='Текст письма'),
                ),
                migrations.AddField(
                    model_name='emailtemplate',
                    name='subject_en',
                    field=models.CharField(help_text='Можно использовать {плейсхолдеры}: {order_number}, {user_name} и т.д.', max_length=300, null=True, verbose_name='Тема письма'),
                ),
                migrations.AddField(
                    model_name='emailtemplate',
                    name='subject_kk',
                    field=models.CharField(help_text='Можно использовать {плейсхолдеры}: {order_number}, {user_name} и т.д.', max_length=300, null=True, verbose_name='Тема письма'),
                ),
                migrations.AddField(
                    model_name='emailtemplate',
                    name='subject_ru',
                    field=models.CharField(help_text='Можно использовать {плейсхолдеры}: {order_number}, {user_name} и т.д.', max_length=300, null=True, verbose_name='Тема письма'),
                ),
            ],
            database_operations=[],
        ),
    ]
