# Generated by Django 5.2.5 on 2026-03-12 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_kk', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Отображается над формой', verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, help_text='Отображается над формой', null=True, verbose_name='Описание')),
                ('description_kk', models.TextField(blank=True, help_text='Отображается над формой', null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, help_text='Отображается над формой', null=True, verbose_name='Описание')),
                ('success_title', models.CharField(default='Спасибо!', max_length=200, verbose_name='Заголовок успеха')),
                ('success_title_ru', models.CharField(default='Спасибо!', max_length=200, null=True, verbose_name='Заголовок успеха')),
                ('success_title_kk', models.CharField(default='Спасибо!', max_length=200, null=True, verbose_name='Заголовок успеха')),
                ('success_title_en', models.CharField(default='Спасибо!', max_length=200, null=True, verbose_name='Заголовок успеха')),
                ('success_text', models.TextField(default='Мы свяжемся с вами в ближайшее время.', verbose_name='Текст успеха')),
                ('success_text_ru', models.TextField(default='Мы свяжемся с вами в ближайшее время.', null=True, verbose_name='Текст успеха')),
                ('success_text_kk', models.TextField(default='Мы свяжемся с вами в ближайшее время.', null=True, verbose_name='Текст успеха')),
                ('success_text_en', models.TextField(default='Мы свяжемся с вами в ближайшее время.', null=True, verbose_name='Текст успеха')),
                ('submit_text', models.CharField(default='Отправить', max_length=100, verbose_name='Текст кнопки')),
                ('submit_text_ru', models.CharField(default='Отправить', max_length=100, null=True, verbose_name='Текст кнопки')),
                ('submit_text_kk', models.CharField(default='Отправить', max_length=100, null=True, verbose_name='Текст кнопки')),
                ('submit_text_en', models.CharField(default='Отправить', max_length=100, null=True, verbose_name='Текст кнопки')),
                ('email_notify_to', models.EmailField(blank=True, help_text='Куда слать уведомление о новой заявке', max_length=254, verbose_name='Email для уведомлений')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='InquirySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Данные')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='inquiries.inquiryform', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Имя поля в JSON (name, email, phone и т.д.)', verbose_name='Ключ поля')),
                ('label', models.CharField(max_length=200, verbose_name='Лейбл')),
                ('label_ru', models.CharField(max_length=200, null=True, verbose_name='Лейбл')),
                ('label_kk', models.CharField(max_length=200, null=True, verbose_name='Лейбл')),
                ('label_en', models.CharField(max_length=200, null=True, verbose_name='Лейбл')),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('textarea', 'Многострочный текст'), ('email', 'Email'), ('phone', 'Телефон'), ('number', 'Число'), ('select', 'Выпадающий список'), ('radio', 'Радио-кнопки'), ('checkbox', 'Чекбокс')], default='text', max_length=20, verbose_name='Тип')),
                ('placeholder', models.CharField(blank=True, max_length=200, verbose_name='Placeholder')),
                ('placeholder_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Placeholder')),
                ('placeholder_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Placeholder')),
                ('placeholder_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Placeholder')),
                ('choices_text', models.TextField(blank=True, help_text='Для select/radio: по одному на строку в формате value|Текст', verbose_name='Варианты')),
                ('choices_text_ru', models.TextField(blank=True, help_text='Для select/radio: по одному на строку в формате value|Текст', null=True, verbose_name='Варианты')),
                ('choices_text_kk', models.TextField(blank=True, help_text='Для select/radio: по одному на строку в формате value|Текст', null=True, verbose_name='Варианты')),
                ('choices_text_en', models.TextField(blank=True, help_text='Для select/radio: по одному на строку в формате value|Текст', null=True, verbose_name='Варианты')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательное')),
                ('min_value', models.IntegerField(blank=True, help_text='Для number', null=True, verbose_name='Мин. значение')),
                ('max_value', models.IntegerField(blank=True, help_text='Для number', null=True, verbose_name='Макс. значение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='inquiries.inquiryform', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Поле формы',
                'verbose_name_plural': 'Поля формы',
                'ordering': ['order'],
                'unique_together': {('form', 'key')},
            },
        ),
    ]
