# Generated by Django 5.2.5 on 2026-03-12 14:38

import django.db.models.deletion
from django.db import migrations, models


def migrate_json_to_fieldvalues(apps, schema_editor):
    """Перенести данные из JSONField в InquiryFieldValue."""
    InquirySubmission = apps.get_model('inquiries', 'InquirySubmission')
    InquiryField = apps.get_model('inquiries', 'InquiryField')
    InquiryFieldValue = apps.get_model('inquiries', 'InquiryFieldValue')

    for sub in InquirySubmission.objects.all():
        if not sub.data:
            continue
        fields_by_key = {
            f.key: f for f in InquiryField.objects.filter(form=sub.form)
        }
        values = []
        for key, val in sub.data.items():
            if key in fields_by_key and val:
                values.append(InquiryFieldValue(
                    submission=sub,
                    field=fields_by_key[key],
                    value=str(val),
                ))
        if values:
            InquiryFieldValue.objects.bulk_create(values)


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        # 1. Создаём InquiryFieldValue
        migrations.CreateModel(
            name='InquiryFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, verbose_name='Значение')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='inquiries.inquiryfield', verbose_name='Поле')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='inquiries.inquirysubmission', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Значение поля',
                'verbose_name_plural': 'Значения полей',
                'unique_together': {('submission', 'field')},
            },
        ),
        # 2. Мигрируем данные из JSON
        migrations.RunPython(migrate_json_to_fieldvalues, migrations.RunPython.noop),
        # 3. Удаляем старое поле
        migrations.RemoveField(
            model_name='inquirysubmission',
            name='data',
        ),
    ]
