# Generated by Django 5.2.5 on 2026-03-19 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_fieldvalue_normalize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('processed', 'Обработана'), ('unprocessed', 'Снята обработка')], max_length=20, verbose_name='Действие')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='inquiries.inquirysubmission', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'История статуса заявки',
                'verbose_name_plural': 'История статусов заявок',
                'ordering': ['-changed_at'],
            },
        ),
    ]
