# Generated by Django 5.2.5 on 2026-03-12 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='q1, q2, q3, q4 — используется в правилах подбора', max_length=20, unique=True, verbose_name='Ключ')),
                ('text', models.TextField(help_text='HTML-перенос строк через <br>', verbose_name='Текст вопроса')),
                ('text_ru', models.TextField(help_text='HTML-перенос строк через <br>', null=True, verbose_name='Текст вопроса')),
                ('text_kk', models.TextField(help_text='HTML-перенос строк через <br>', null=True, verbose_name='Текст вопроса')),
                ('text_en', models.TextField(help_text='HTML-перенос строк через <br>', null=True, verbose_name='Текст вопроса')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Вопрос квиза',
                'verbose_name_plural': 'Вопросы квиза',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizResultText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Твой<br>идеальный<br>DR.JOYS', help_text='HTML-перенос строк через <br>', verbose_name='Заголовок результата')),
                ('title_ru', models.TextField(default='Твой<br>идеальный<br>DR.JOYS', help_text='HTML-перенос строк через <br>', null=True, verbose_name='Заголовок результата')),
                ('title_kk', models.TextField(default='Твой<br>идеальный<br>DR.JOYS', help_text='HTML-перенос строк через <br>', null=True, verbose_name='Заголовок результата')),
                ('title_en', models.TextField(default='Твой<br>идеальный<br>DR.JOYS', help_text='HTML-перенос строк через <br>', null=True, verbose_name='Заголовок результата')),
                ('button_text', models.CharField(default='Купить', max_length=100, verbose_name='Текст кнопки')),
                ('button_text_ru', models.CharField(default='Купить', max_length=100, null=True, verbose_name='Текст кнопки')),
                ('button_text_kk', models.CharField(default='Купить', max_length=100, null=True, verbose_name='Текст кнопки')),
                ('button_text_en', models.CharField(default='Купить', max_length=100, null=True, verbose_name='Текст кнопки')),
                ('more_text', models.CharField(default='Ещё вариант', max_length=100, verbose_name='Текст «ещё вариант»')),
                ('more_text_ru', models.CharField(default='Ещё вариант', max_length=100, null=True, verbose_name='Текст «ещё вариант»')),
                ('more_text_kk', models.CharField(default='Ещё вариант', max_length=100, null=True, verbose_name='Текст «ещё вариант»')),
                ('more_text_en', models.CharField(default='Ещё вариант', max_length=100, null=True, verbose_name='Текст «ещё вариант»')),
            ],
            options={
                'verbose_name': 'Тексты результата квиза',
                'verbose_name_plural': 'Тексты результата квиза',
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='texture, aroma, banana, yes, no — передаётся в правила', max_length=50, verbose_name='Значение')),
                ('label', models.CharField(max_length=200, verbose_name='Текст кнопки')),
                ('label_ru', models.CharField(max_length=200, null=True, verbose_name='Текст кнопки')),
                ('label_kk', models.CharField(max_length=200, null=True, verbose_name='Текст кнопки')),
                ('label_en', models.CharField(max_length=200, null=True, verbose_name='Текст кнопки')),
                ('bg_color', models.CharField(blank=True, help_text='CSS-цвет, например #E8C840', max_length=30, verbose_name='Цвет фона')),
                ('text_color', models.CharField(blank=True, help_text='CSS-цвет, например #fff', max_length=30, verbose_name='Цвет текста')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.quizquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
                'ordering': ['order'],
            },
        ),
    ]
