# Generated by Django 5.2.5 on 2026-03-19 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_image_alt_text_i18n'),
        ('quiz', '0002_quizquestion_quizresulttext_quizoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(blank=True, max_length=50, verbose_name='Q1')),
                ('q2', models.CharField(blank=True, max_length=50, verbose_name='Q2')),
                ('q3', models.CharField(blank=True, max_length=50, verbose_name='Q3')),
                ('q4', models.CharField(blank=True, max_length=50, verbose_name='Q4')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Сессия')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
                ('result_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_submissions', to='catalog.product', verbose_name='Рекомендованный товар')),
            ],
            options={
                'verbose_name': 'Прохождение квиза',
                'verbose_name_plural': 'Прохождения квиза',
                'ordering': ['-created_at'],
            },
        ),
    ]
