# Generated by Django 5.2.5 on 2026-02-28 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория блога',
                'verbose_name_plural': 'Категории блога',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='Заголовок')),
                ('title_kk', models.CharField(max_length=300, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='URL страницы: about, partners, contacts', max_length=300, unique=True, verbose_name='Slug')),
                ('body', models.TextField(help_text='HTML-контент страницы', verbose_name='Контент')),
                ('body_ru', models.TextField(help_text='HTML-контент страницы', null=True, verbose_name='Контент')),
                ('body_kk', models.TextField(help_text='HTML-контент страницы', null=True, verbose_name='Контент')),
                ('body_en', models.TextField(help_text='HTML-контент страницы', null=True, verbose_name='Контент')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='META Title')),
                ('meta_title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='META Title')),
                ('meta_title_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='META Title')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='META Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='META Description')),
                ('meta_description_ru', models.TextField(blank=True, null=True, verbose_name='META Description')),
                ('meta_description_kk', models.TextField(blank=True, null=True, verbose_name='META Description')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='META Description')),
                ('og_image', models.ImageField(blank=True, upload_to='pages/og/', verbose_name='OG Image')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='Заголовок')),
                ('title_kk', models.CharField(max_length=300, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, help_text='Текст для карточки в списке блога', verbose_name='Краткое описание')),
                ('excerpt_ru', models.TextField(blank=True, help_text='Текст для карточки в списке блога', null=True, verbose_name='Краткое описание')),
                ('excerpt_kk', models.TextField(blank=True, help_text='Текст для карточки в списке блога', null=True, verbose_name='Краткое описание')),
                ('excerpt_en', models.TextField(blank=True, help_text='Текст для карточки в списке блога', null=True, verbose_name='Краткое описание')),
                ('body', models.TextField(help_text='HTML-контент статьи', verbose_name='Контент')),
                ('body_ru', models.TextField(help_text='HTML-контент статьи', null=True, verbose_name='Контент')),
                ('body_kk', models.TextField(help_text='HTML-контент статьи', null=True, verbose_name='Контент')),
                ('body_en', models.TextField(help_text='HTML-контент статьи', null=True, verbose_name='Контент')),
                ('cover_image', models.ImageField(blank=True, upload_to='blog/covers/', verbose_name='Обложка')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Автор')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='META Title')),
                ('meta_title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='META Title')),
                ('meta_title_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='META Title')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='META Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='META Description')),
                ('meta_description_ru', models.TextField(blank=True, null=True, verbose_name='META Description')),
                ('meta_description_kk', models.TextField(blank=True, null=True, verbose_name='META Description')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='META Description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='pages.blogcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['slug'], name='pages_blogp_slug_5d798f_idx'), models.Index(fields=['-published_at', 'is_published'], name='pages_blogp_publish_dd627a_idx')],
            },
        ),
    ]
