# Generated by Django 5.2.5 on 2026-03-18 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('title_kk', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('position', models.CharField(choices=[('header', 'Шапка'), ('footer', 'Подвал')], default='header', max_length=10, verbose_name='Позиция')),
                ('link_type', models.CharField(choices=[('route', 'Маршрут Django'), ('page', 'Страница CMS'), ('url', 'Внешняя ссылка')], default='route', max_length=10, verbose_name='Тип ссылки')),
                ('named_url', models.CharField(blank=True, help_text='Например: home, catalog:catalog, pages:blog_list', max_length=200, verbose_name='Маршрут Django')),
                ('external_url', models.URLField(blank=True, help_text='URL для редиректа (для типа «Внешняя ссылка»)', verbose_name='Внешняя ссылка')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='Открывать в новой вкладке')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('page', models.ForeignKey(blank=True, help_text='Выбрать страницу (для типа «Страница CMS»)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.page', verbose_name='Страница CMS')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Навигация',
                'ordering': ['position', 'order'],
                'indexes': [models.Index(fields=['position', 'is_active', 'order'], name='pages_menui_positio_f88ee7_idx')],
            },
        ),
    ]
