# Generated by Django 5.2.5 on 2026-03-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_menuitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order'], 'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Навигация'},
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='pages_menui_positio_f88ee7_idx',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='position',
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_active', 'order'], name='pages_menui_is_acti_910308_idx'),
        ),
    ]
