# Generated by Django 5.2.5 on 2026-03-18 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pagecategory_alter_page_options_page_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='page_category',
            field=models.ForeignKey(blank=True, help_text='Выбрать категорию (для типа «Категория страниц»)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.pagecategory', verbose_name='Категория страниц'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_type',
            field=models.CharField(choices=[('route', 'Маршрут Django'), ('page', 'Страница CMS'), ('category', 'Категория страниц'), ('url', 'Внешняя ссылка')], default='route', max_length=10, verbose_name='Тип ссылки'),
        ),
    ]
