# Generated by Django 5.2.5 on 2026-03-18 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_menuitem_page_category_alter_menuitem_link_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок (H1)')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='Заголовок (H1)')),
                ('title_kk', models.CharField(max_length=300, null=True, verbose_name='Заголовок (H1)')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Заголовок (H1)')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок (H2)')),
                ('subtitle_ru', models.TextField(blank=True, null=True, verbose_name='Подзаголовок (H2)')),
                ('subtitle_kk', models.TextField(blank=True, null=True, verbose_name='Подзаголовок (H2)')),
                ('subtitle_en', models.TextField(blank=True, null=True, verbose_name='Подзаголовок (H2)')),
                ('button_catalog_text', models.CharField(default='В каталог', max_length=100, verbose_name='Текст кнопки «Каталог»')),
                ('button_catalog_text_ru', models.CharField(default='В каталог', max_length=100, null=True, verbose_name='Текст кнопки «Каталог»')),
                ('button_catalog_text_kk', models.CharField(default='В каталог', max_length=100, null=True, verbose_name='Текст кнопки «Каталог»')),
                ('button_catalog_text_en', models.CharField(default='В каталог', max_length=100, null=True, verbose_name='Текст кнопки «Каталог»')),
                ('button_buy_text', models.CharField(default='Купить', max_length=100, verbose_name='Текст кнопки «Купить»')),
                ('button_buy_text_ru', models.CharField(default='Купить', max_length=100, null=True, verbose_name='Текст кнопки «Купить»')),
                ('button_buy_text_kk', models.CharField(default='Купить', max_length=100, null=True, verbose_name='Текст кнопки «Купить»')),
                ('button_buy_text_en', models.CharField(default='Купить', max_length=100, null=True, verbose_name='Текст кнопки «Купить»')),
                ('button_buy_url', models.CharField(blank=True, help_text='Произвольный URL, например: https://example.com/promo', max_length=500, verbose_name='Ссылка кнопки «Купить»')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Hero главной',
                'verbose_name_plural': 'Hero главной',
            },
        ),
        migrations.CreateModel(
            name='HeroCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/cards/', verbose_name='Изображение товара')),
                ('count', models.PositiveIntegerField(help_text='Число на карточке: 5, 17, 30 и т.д.', verbose_name='Количество (шт.)')),
                ('count_image', models.ImageField(blank=True, help_text='SVG/PNG с числом. Если не загружено — число выводится текстом.', upload_to='hero/counters/', verbose_name='Картинка счётчика')),
                ('gradient_from', models.CharField(default='#ACE143', help_text='HEX-цвет, например: #ACE143', max_length=7, verbose_name='Градиент от')),
                ('gradient_to', models.CharField(default='#D7E422', help_text='HEX-цвет, например: #D7E422', max_length=7, verbose_name='Градиент до')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='pages.herosection', verbose_name='Hero')),
            ],
            options={
                'verbose_name': 'Карточка hero',
                'verbose_name_plural': 'Карточки hero',
                'ordering': ['order'],
            },
        ),
    ]
