# Generated by Django 5.2.5 on 2026-03-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_herosection_herocard'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='Заголовок')),
                ('title_kk', models.CharField(max_length=300, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('text_ru', models.TextField(null=True, verbose_name='Текст')),
                ('text_kk', models.TextField(null=True, verbose_name='Текст')),
                ('text_en', models.TextField(null=True, verbose_name='Текст')),
                ('media_type', models.CharField(choices=[('image', 'Картинка'), ('video', 'Видео')], default='image', max_length=5, verbose_name='Тип контента')),
                ('image', models.ImageField(blank=True, help_text='Фоновое изображение слайда', upload_to='features/', verbose_name='Картинка')),
                ('video', models.FileField(blank=True, help_text='MP4 видео для фона слайда', upload_to='features/videos/', verbose_name='Видео')),
                ('video_poster', models.ImageField(blank=True, help_text='Превью-картинка пока видео загружается', upload_to='features/posters/', verbose_name='Обложка видео')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Слайд Features',
                'verbose_name_plural': 'Слайды Features',
                'ordering': ['order'],
            },
        ),
    ]
