# Generated by Django 5.2.5 on 2026-03-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_featureslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.TextField(verbose_name='Заголовок (H1)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title_en',
            field=models.TextField(null=True, verbose_name='Заголовок (H1)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title_kk',
            field=models.TextField(null=True, verbose_name='Заголовок (H1)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title_ru',
            field=models.TextField(null=True, verbose_name='Заголовок (H1)'),
        ),
    ]
