# Generated by Django 5.2.5 on 2026-03-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_herosection_title_alter_herosection_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herocard',
            name='count_image',
        ),
        migrations.RemoveField(
            model_name='herocard',
            name='gradient_from',
        ),
        migrations.RemoveField(
            model_name='herocard',
            name='gradient_to',
        ),
        migrations.AlterField(
            model_name='herocard',
            name='count',
            field=models.PositiveIntegerField(help_text='Число на карточке: 5, 17, 30 и т.д.', verbose_name='Количество в пачке'),
        ),
    ]
