# Generated by Django 5.2.5 on 2026-03-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_herocard_count_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocard',
            name='count_image',
            field=models.FileField(blank=True, help_text='SVG-картинка с числом (5.svg, 17.svg, 30.svg)', upload_to='hero/counter/', verbose_name='SVG кол-ва'),
        ),
    ]
