# Generated by Django 5.2.5 on 2026-03-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_herocard_count_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herocard',
            name='count',
        ),
    ]
