# Generated by Django 5.2.5 on 2026-03-18 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_herocard_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Уникальный ключ: quiz, partners, tattoo', unique=True, verbose_name='Ключ')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('title_ru', models.TextField(null=True, verbose_name='Заголовок')),
                ('title_kk', models.TextField(null=True, verbose_name='Заголовок')),
                ('title_en', models.TextField(null=True, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('subtitle_ru', models.TextField(blank=True, null=True, verbose_name='Подзаголовок')),
                ('subtitle_kk', models.TextField(blank=True, null=True, verbose_name='Подзаголовок')),
                ('subtitle_en', models.TextField(blank=True, null=True, verbose_name='Подзаголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_kk', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('button_text', models.CharField(blank=True, max_length=200, verbose_name='Текст кнопки')),
                ('button_text_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст кнопки')),
                ('button_text_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст кнопки')),
                ('button_text_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(blank=True, help_text='URL или пусто если кнопка открывает модалку', max_length=500, verbose_name='Ссылка кнопки')),
                ('image', models.ImageField(blank=True, upload_to='promo/', verbose_name='Основная картинка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Промо-блок',
                'verbose_name_plural': 'Промо-блоки',
            },
        ),
        migrations.CreateModel(
            name='PromoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='promo/gallery/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.promoblock', verbose_name='Промо-блок')),
            ],
            options={
                'verbose_name': 'Картинка промо',
                'verbose_name_plural': 'Картинки промо',
                'ordering': ['order'],
            },
        ),
    ]
