# Generated by Django 5.2.5 on 2026-03-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_promoblock_promoimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='email_verify, password_reset, welcome, order_created, order_paid, order_shipped', max_length=100, unique=True, verbose_name='Ключ')),
                ('subject', models.CharField(help_text='Можно использовать {плейсхолдеры}: {order_number}, {user_name} и т.д.', max_length=300, verbose_name='Тема письма')),
                ('subject_ru', models.CharField(help_text='Можно использовать {плейсхолдеры}: {order_number}, {user_name} и т.д.', max_length=300, null=True, verbose_name='Тема письма')),
                ('subject_kk', models.CharField(help_text='Можно использовать {плейсхолдеры}: {order_number}, {user_name} и т.д.', max_length=300, null=True, verbose_name='Тема письма')),
                ('subject_en', models.CharField(help_text='Можно использовать {плейсхолдеры}: {order_number}, {user_name} и т.д.', max_length=300, null=True, verbose_name='Тема письма')),
                ('body', models.TextField(help_text='Плейн-текст. Плейсхолдеры: {user_name}, {verify_url}, {order_number} и т.д.', verbose_name='Текст письма')),
                ('body_ru', models.TextField(help_text='Плейн-текст. Плейсхолдеры: {user_name}, {verify_url}, {order_number} и т.д.', null=True, verbose_name='Текст письма')),
                ('body_kk', models.TextField(help_text='Плейн-текст. Плейсхолдеры: {user_name}, {verify_url}, {order_number} и т.д.', null=True, verbose_name='Текст письма')),
                ('body_en', models.TextField(help_text='Плейн-текст. Плейсхолдеры: {user_name}, {verify_url}, {order_number} и т.д.', null=True, verbose_name='Текст письма')),
                ('description', models.TextField(blank=True, help_text='Какие плейсхолдеры доступны, когда отправляется', verbose_name='Описание (для админа)')),
            ],
            options={
                'verbose_name': 'Шаблон письма',
                'verbose_name_plural': 'Шаблоны писем',
                'ordering': ['slug'],
            },
        ),
    ]
