# Generated by Django 5.2.5 on 2026-03-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='check_email, email_verified, email_error', max_length=100, unique=True, verbose_name='Ключ')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='Заголовок')),
                ('title_kk', models.CharField(max_length=300, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('button_text', models.CharField(blank=True, max_length=200, verbose_name='Текст кнопки')),
                ('button_text_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст кнопки')),
                ('button_text_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст кнопки')),
                ('button_text_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(blank=True, default='/', max_length=500, verbose_name='Ссылка кнопки')),
            ],
            options={
                'verbose_name': 'Служебная страница',
                'verbose_name_plural': 'Служебные страницы',
                'ordering': ['slug'],
            },
        ),
    ]
