# Generated by Django 5.2.5 on 2026-07-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_featureslide_text_color_image_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureslide',
            name='video_mobile',
            field=models.FileField(blank=True, help_text='Опционально. Вертикальный кроп для мобильных. Если не указано — используется десктопное, но у горизонтального видео на узкой карточке будут обрезаны бока.', upload_to='features/videos/mobile/', verbose_name='Видео (мобильное)'),
        ),
        migrations.AlterField(
            model_name='featureslide',
            name='text_en',
            field=models.TextField(help_text='Поддерживает HTML-теги. Для ссылок используйте &lt;a href="..."&gt;...&lt;/a&gt;', null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='featureslide',
            name='text_kk',
            field=models.TextField(help_text='Поддерживает HTML-теги. Для ссылок используйте &lt;a href="..."&gt;...&lt;/a&gt;', null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='featureslide',
            name='text_ru',
            field=models.TextField(help_text='Поддерживает HTML-теги. Для ссылок используйте &lt;a href="..."&gt;...&lt;/a&gt;', null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='featureslide',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 видео для фона слайда. Используется на десктопе и как фолбэк для мобильных.', upload_to='features/videos/', verbose_name='Видео (десктоп)'),
        ),
    ]
