# Generated by Django 5.2.16 on 2026-07-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_featureslide_video_mobile_alter_featureslide_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='В международном формате, только + и цифры: +77766103836', max_length=32, verbose_name='Телефон')),
                ('whatsapp_phone', models.CharField(blank=True, help_text='Если пусто — используется основной телефон', max_length=32, verbose_name='Телефон WhatsApp')),
                ('telegram_username', models.CharField(blank=True, help_text='Имя пользователя: drjoysoriginal. Можно вставить с @ или ссылкой — приведём к имени сами. Пусто — канал не показывается', max_length=64, verbose_name='Telegram')),
                ('email', models.EmailField(blank=True, help_text='Пусто — канал не показывается', max_length=254, verbose_name='Email')),
                ('instagram_url', models.URLField(blank=True, help_text='Полная ссылка. Пусто — иконка не показывается', max_length=300, verbose_name='Instagram')),
                ('tiktok_url', models.URLField(blank=True, help_text='Полная ссылка. Пусто — иконка не показывается', max_length=300, verbose_name='TikTok')),
                ('youtube_url', models.URLField(blank=True, help_text='Полная ссылка. Пусто — иконка не показывается', max_length=300, verbose_name='YouTube')),
                ('marketplace_url', models.URLField(blank=True, help_text='Витрина на Wildberries или другом маркетплейсе. Пусто — ссылки нет', max_length=300, verbose_name='Маркетплейс')),
                ('legal_name', models.CharField(help_text='Как в свидетельстве: ТОО «DR JOYS»', max_length=200, verbose_name='Юридическое название')),
                ('legal_name_ru', models.CharField(help_text='Как в свидетельстве: ТОО «DR JOYS»', max_length=200, null=True, verbose_name='Юридическое название')),
                ('legal_name_kk', models.CharField(help_text='Как в свидетельстве: ТОО «DR JOYS»', max_length=200, null=True, verbose_name='Юридическое название')),
                ('legal_name_en', models.CharField(help_text='Как в свидетельстве: ТОО «DR JOYS»', max_length=200, null=True, verbose_name='Юридическое название')),
                ('bin', models.CharField(help_text='12 цифр', max_length=12, verbose_name='БИН')),
                ('bin_label', models.CharField(help_text='Как называется код на этом языке: БИН / БСН / BIN', max_length=16, verbose_name='Подпись БИН')),
                ('bin_label_ru', models.CharField(help_text='Как называется код на этом языке: БИН / БСН / BIN', max_length=16, null=True, verbose_name='Подпись БИН')),
                ('bin_label_kk', models.CharField(help_text='Как называется код на этом языке: БИН / БСН / BIN', max_length=16, null=True, verbose_name='Подпись БИН')),
                ('bin_label_en', models.CharField(help_text='Как называется код на этом языке: БИН / БСН / BIN', max_length=16, null=True, verbose_name='Подпись БИН')),
                ('address_locality', models.CharField(help_text='Без приставки «г.»: Астана', max_length=100, verbose_name='Город')),
                ('address_locality_ru', models.CharField(help_text='Без приставки «г.»: Астана', max_length=100, null=True, verbose_name='Город')),
                ('address_locality_kk', models.CharField(help_text='Без приставки «г.»: Астана', max_length=100, null=True, verbose_name='Город')),
                ('address_locality_en', models.CharField(help_text='Без приставки «г.»: Астана', max_length=100, null=True, verbose_name='Город')),
                ('address_street', models.CharField(help_text='Без города: р-н Байконыр, ул. А. Бараева, д. 13, н.п. 5', max_length=255, verbose_name='Улица, дом')),
                ('address_street_ru', models.CharField(help_text='Без города: р-н Байконыр, ул. А. Бараева, д. 13, н.п. 5', max_length=255, null=True, verbose_name='Улица, дом')),
                ('address_street_kk', models.CharField(help_text='Без города: р-н Байконыр, ул. А. Бараева, д. 13, н.п. 5', max_length=255, null=True, verbose_name='Улица, дом')),
                ('address_street_en', models.CharField(help_text='Без города: р-н Байконыр, ул. А. Бараева, д. 13, н.п. 5', max_length=255, null=True, verbose_name='Улица, дом')),
                ('work_hours', models.CharField(blank=True, help_text='Пн–Пт 10:00–19:00. Пусто — адрес показывается без графика', max_length=120, verbose_name='Часы работы')),
                ('work_hours_ru', models.CharField(blank=True, help_text='Пн–Пт 10:00–19:00. Пусто — адрес показывается без графика', max_length=120, null=True, verbose_name='Часы работы')),
                ('work_hours_kk', models.CharField(blank=True, help_text='Пн–Пт 10:00–19:00. Пусто — адрес показывается без графика', max_length=120, null=True, verbose_name='Часы работы')),
                ('work_hours_en', models.CharField(blank=True, help_text='Пн–Пт 10:00–19:00. Пусто — адрес показывается без графика', max_length=120, null=True, verbose_name='Часы работы')),
                ('office_lat', models.DecimalField(blank=True, decimal_places=6, help_text='Широта офиса, как в 2ГИС: 51.158240', max_digits=9, null=True, verbose_name='Широта')),
                ('office_lng', models.DecimalField(blank=True, decimal_places=6, help_text='Долгота офиса, как в 2ГИС: 71.435760', max_digits=9, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Контакты компании',
                'verbose_name_plural': 'Контакты компании',
            },
        ),
    ]
