# Generated by Django 5.2.16 on 2026-07-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_clear_contacts_page_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='Без приставки «г.»: Алматы. Чипы городов на странице собираются из этого поля', max_length=100, verbose_name='Город')),
                ('name', models.CharField(max_length=200, verbose_name='Магазин')),
                ('address', models.CharField(help_text='Без города: Ермека Серкебаева, 287Б', max_length=255, verbose_name='Адрес')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, help_text='Пусто — возьмём из ссылки 2ГИС при сохранении', max_digits=9, null=True, verbose_name='Широта')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('map_url', models.URLField(blank=True, help_text='Ссылка на карточку точки в 2ГИС — из неё же извлекаются координаты', max_length=500, verbose_name='Ссылка 2ГИС')),
                ('fulfillment', models.CharField(choices=[('pickup_delivery', 'Самовывоз и доставка'), ('pickup', 'Только самовывоз')], default='pickup_delivery', max_length=20, verbose_name='Формат')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Оффлайн точка',
                'verbose_name_plural': 'Оффлайн точки',
                'ordering': ['city', 'order', 'name', 'address'],
                'indexes': [models.Index(fields=['is_active', 'city'], name='pages_offli_is_acti_d825f2_idx')],
            },
        ),
    ]
