# Generated by Django 5.2.16 on 2026-08-09 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_category_contraindications_page_and_more'),
        ('pages', '0021_offlinestore'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocard',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Страница товара, куда ведёт карточка (и кнопка «Купить» на мобильных, пока карточка активна)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_cards', to='catalog.product', verbose_name='Товар'),
        ),
    ]
