# Generated by Django 5.2.16 on 2026-08-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_herocard_link_classic_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureslide',
            name='button_color',
            field=models.CharField(choices=[('white', 'Белая'), ('red', 'Красная')], default='white', max_length=10, verbose_name='Цвет кнопки'),
        ),
        migrations.AddField(
            model_name='featureslide',
            name='button_text',
            field=models.CharField(blank=True, help_text='Кнопка выводится, только если заполнены и текст, и ссылка', max_length=100, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='featureslide',
            name='button_text_en',
            field=models.CharField(blank=True, help_text='Кнопка выводится, только если заполнены и текст, и ссылка', max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='featureslide',
            name='button_text_kk',
            field=models.CharField(blank=True, help_text='Кнопка выводится, только если заполнены и текст, и ссылка', max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='featureslide',
            name='button_text_ru',
            field=models.CharField(blank=True, help_text='Кнопка выводится, только если заполнены и текст, и ссылка', max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='featureslide',
            name='button_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка кнопки'),
        ),
    ]
