# Generated by Django 5.2.5 on 2026-03-05 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0015_alter_product_pack_quantity_delete_quizrule'),
    ]

    operations = [
        # Новые модели — обычное создание
        migrations.CreateModel(
            name='PartnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('region', models.CharField(max_length=200, verbose_name='Регион / город')),
                ('interest', models.CharField(choices=[('ready', 'Готов к сотрудничеству'), ('exploring', 'Изучаю возможности')], max_length=20, verbose_name='Интерес')),
                ('format', models.CharField(choices=[('country_dist', 'Дистрибьютор по стране'), ('city_dist', 'Дистрибьютор по городу'), ('wholesale', 'Оптовые закупки'), ('offline', 'Офлайн-точка')], max_length=20, verbose_name='Формат сотрудничества')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('contact_method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('call', 'Звонок')], max_length=20, verbose_name='Способ связи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Заявка партнёра',
                'verbose_name_plural': 'Заявки партнёров',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='banana, strawberry, chocolate, dotted-ribbed, triple-lube', unique=True, verbose_name='Ключ')),
                ('image', models.ImageField(upload_to='quiz/backgrounds/', verbose_name='Изображение')),
                ('is_dark_theme', models.BooleanField(default=False, help_text='Белый текст на тёмном фоне', verbose_name='Тёмная тема')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Фон квиза',
                'verbose_name_plural': 'Фоны квиза',
            },
        ),
        migrations.CreateModel(
            name='TattooRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('city', models.CharField(max_length=200, verbose_name='Город')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Заявка на тату',
                'verbose_name_plural': 'Заявки на тату',
                'ordering': ['-created_at'],
            },
        ),
        # QuizRule — переносим из catalog: state-only CreateModel + DB rename
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='QuizRule',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('q1_important', models.CharField(blank=True, choices=[('texture', 'Текстура'), ('aroma', 'Аромат'), ('feel', 'Неощутимость')], max_length=20, verbose_name='Q1: Что важнее?')),
                        ('q2_aroma', models.CharField(blank=True, choices=[('banana', 'Банан'), ('strawberry', 'Клубника'), ('chocolate', 'Шоколад'), ('none', 'Без аромата')], max_length=20, verbose_name='Q2: Аромат')),
                        ('q3_frequency', models.CharField(blank=True, choices=[('daily', 'Каждый день'), ('weekly', 'Несколько раз в неделю'), ('monthly', 'Несколько раз в месяц'), ('yearly', 'Редко')], max_length=20, verbose_name='Q3: Частота')),
                        ('q4_lube', models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет')], max_length=10, verbose_name='Q4: Доп. смазка?')),
                        ('priority', models.IntegerField(default=0, help_text='Чем выше — тем приоритетнее. При совпадении нескольких правил побеждает с высшим.', verbose_name='Приоритет')),
                        ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                        ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_rules', to='catalog.product', verbose_name='Рекомендуемый товар')),
                    ],
                    options={
                        'verbose_name': 'Правило квиза',
                        'verbose_name_plural': 'Правила квиза',
                        'ordering': ['-priority'],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE catalog_quizrule RENAME TO modals_quizrule;',
                    reverse_sql='ALTER TABLE modals_quizrule RENAME TO catalog_quizrule;',
                ),
            ],
        ),
    ]
