# Generated by Django 5.2.5 on 2026-03-12 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
        ('modals', '0002_remove_quiz_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('title', models.CharField(help_text='Для админки, не отображается', max_length=200, verbose_name='Название')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная')], default='dark', max_length=10, verbose_name='Тема')),
                ('trigger_text', models.CharField(blank=True, help_text='Текст кнопки, открывающей модалку (например «Прочитать условие»)', max_length=200, verbose_name='Текст кнопки-триггера')),
                ('trigger_text_ru', models.CharField(blank=True, help_text='Текст кнопки, открывающей модалку (например «Прочитать условие»)', max_length=200, null=True, verbose_name='Текст кнопки-триггера')),
                ('trigger_text_kk', models.CharField(blank=True, help_text='Текст кнопки, открывающей модалку (например «Прочитать условие»)', max_length=200, null=True, verbose_name='Текст кнопки-триггера')),
                ('trigger_text_en', models.CharField(blank=True, help_text='Текст кнопки, открывающей модалку (например «Прочитать условие»)', max_length=200, null=True, verbose_name='Текст кнопки-триггера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Интерактивная модалка',
                'verbose_name_plural': 'Интерактивные модалки',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ModalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('step_type', models.CharField(choices=[('content', 'Контент (картинка + текст + «Далее»)'), ('form', 'Форма из inquiries'), ('cta', 'CTA-кнопка (ссылка)')], default='content', max_length=10, verbose_name='Тип шага')),
                ('image', models.ImageField(blank=True, upload_to='modals/', verbose_name='Картинка')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_kk', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('button_text', models.CharField(default='Далее', max_length=100, verbose_name='Текст кнопки «Далее»')),
                ('button_text_ru', models.CharField(default='Далее', max_length=100, null=True, verbose_name='Текст кнопки «Далее»')),
                ('button_text_kk', models.CharField(default='Далее', max_length=100, null=True, verbose_name='Текст кнопки «Далее»')),
                ('button_text_en', models.CharField(default='Далее', max_length=100, null=True, verbose_name='Текст кнопки «Далее»')),
                ('badge_text', models.CharField(blank=True, help_text='Например «21+»', max_length=20, verbose_name='Бейдж')),
                ('badge_text_ru', models.CharField(blank=True, help_text='Например «21+»', max_length=20, null=True, verbose_name='Бейдж')),
                ('badge_text_kk', models.CharField(blank=True, help_text='Например «21+»', max_length=20, null=True, verbose_name='Бейдж')),
                ('badge_text_en', models.CharField(blank=True, help_text='Например «21+»', max_length=20, null=True, verbose_name='Бейдж')),
                ('cta_text', models.CharField(blank=True, max_length=200, verbose_name='Текст CTA-кнопки')),
                ('cta_text_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст CTA-кнопки')),
                ('cta_text_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст CTA-кнопки')),
                ('cta_text_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст CTA-кнопки')),
                ('cta_url', models.URLField(blank=True, verbose_name='Ссылка CTA')),
                ('inquiry_form', models.ForeignKey(blank=True, help_text='Для типа «Форма» — какую форму из inquiries встроить', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiries.inquiryform', verbose_name='Форма (inquiries)')),
                ('modal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='modals.interactivemodal', verbose_name='Модалка')),
            ],
            options={
                'verbose_name': 'Шаг модалки',
                'verbose_name_plural': 'Шаги модалки',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='PartnerRequest',
        ),
        migrations.DeleteModel(
            name='TattooRequest',
        ),
    ]
