# Generated by Django 5.2.5 on 2026-03-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Покупатель'), ('manager', 'Менеджер'), ('super_manager', 'Супер-менеджер'), ('owner', 'Владелец')], db_index=True, default='customer', max_length=20, verbose_name='Роль'),
        ),
    ]
