# Generated by Django 5.2.5 on 2026-03-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Последний IP'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_user_agent',
            field=models.CharField(blank=True, max_length=300, verbose_name='Браузер'),
        ),
    ]
