# Generated by Django 5.2.16 on 2026-08-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_last_ip_user_last_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Покупатель'), ('manager', 'Менеджер'), ('super_manager', 'Супер-менеджер'), ('owner', 'Владелец'), ('store_manager', 'Менеджер точек')], db_index=True, default='customer', max_length=20, verbose_name='Роль'),
        ),
    ]
