# Generated by Django 5.2.5 on 2026-03-12 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0016_image_alt_text_i18n'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='WB ID')),
                ('nm_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='nmId (артикул WB)')),
                ('product_name', models.CharField(blank=True, max_length=500, verbose_name='Название товара (WB)')),
                ('supplier_article', models.CharField(blank=True, max_length=100, verbose_name='Артикул поставщика')),
                ('user_name', models.CharField(blank=True, max_length=200, verbose_name='Имя автора')),
                ('rating', models.PositiveSmallIntegerField(help_text='1-5', verbose_name='Оценка')),
                ('text', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('pros', models.TextField(blank=True, verbose_name='Достоинства')),
                ('cons', models.TextField(blank=True, verbose_name='Недостатки')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Теги (bables)')),
                ('photos', models.JSONField(blank=True, default=list, help_text='Список URL: [{fullSize, miniSize}]', verbose_name='Фото')),
                ('answer_text', models.TextField(blank=True, verbose_name='Ответ продавца')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Показать на сайте')),
                ('wb_created_at', models.DateTimeField(verbose_name='Дата на WB')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Синхронизировано')),
                ('product', models.ForeignKey(blank=True, help_text='Привязка к товару в каталоге (опционально)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wb_reviews', to='catalog.product', verbose_name='Товар на сайте')),
            ],
            options={
                'verbose_name': 'Отзыв WB',
                'verbose_name_plural': 'Отзывы WB',
                'ordering': ['-wb_created_at'],
                'indexes': [models.Index(fields=['is_featured', '-wb_created_at'], name='reviews_rev_is_feat_8feffc_idx'), models.Index(fields=['rating'], name='reviews_rev_rating_2db6dd_idx')],
            },
        ),
    ]
