# Generated by Django 5.2.5 on 2026-03-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedReview',
            fields=[
            ],
            options={
                'verbose_name': 'Опубликованный отзыв',
                'verbose_name_plural': 'Опубликованные отзывы на сайте',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reviews.review',),
        ),
        migrations.AddField(
            model_name='review',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False, help_text='Всегда показывается на сайте (не участвует в ротации)', verbose_name='Закреплён вручную'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Закреплённые + авто-ротация. Управляется командой rotate_featured_reviews.', verbose_name='Показать на сайте'),
        ),
    ]
