# Generated by Django 5.2.5 on 2026-03-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_excluded',
            field=models.BooleanField(db_index=True, default=False, help_text='Отзыв чужого магазина (OTAKU SHOP и т.д.). Учитывается в статистике, но не показывается на сайте.', verbose_name='Исключён из выборки'),
        ),
    ]
