# Generated by Django 5.2.5 on 2026-07-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_is_excluded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='wb_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='WB ID'),
        ),
    ]
