# Generated by Django 5.2.5 on 2026-02-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO-код: kz, ru, uz, kg, int', max_length=5, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('currency_code', models.CharField(help_text='ISO 4217: KZT, RUB, UZS, USD', max_length=3, verbose_name='Код валюты')),
                ('currency_symbol', models.CharField(help_text='₸, ₽, $', max_length=5, verbose_name='Символ валюты')),
                ('default_language', models.CharField(default='ru', max_length=5, verbose_name='Язык по умолчанию')),
                ('phone_code', models.CharField(default='+7', max_length=5, verbose_name='Телефонный код')),
                ('flag_emoji', models.CharField(blank=True, help_text='Emoji: 🇰🇿, 🇷🇺', max_length=10, verbose_name='Флаг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_default', models.BooleanField(default=False, help_text='Только один регион может быть по умолчанию', verbose_name='По умолчанию')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['order', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_region')],
            },
        ),
    ]
