# Generated by Django 5.2.5 on 2026-03-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_region_name_en_region_name_kk_region_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='payment_gateway',
            field=models.CharField(blank=True, help_text='Код шлюза: vtb, halyk. Пусто = без онлайн-оплаты', max_length=20, verbose_name='Платёжный шлюз'),
        ),
    ]
