# Generated by Django 5.2.5 on 2026-03-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_payment_gateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(help_text='ISO 4217: RUB, USD, EUR', max_length=3, unique=True, verbose_name='Валюта')),
                ('rate', models.DecimalField(decimal_places=4, help_text='KZT за quant единиц валюты', max_digits=12, verbose_name='Курс')),
                ('quant', models.PositiveIntegerField(default=1, help_text='Базовое кол-во единиц (1, 10, 100)', verbose_name='Количество')),
                ('fetched_at', models.DateTimeField(verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
        migrations.AddField(
            model_name='region',
            name='payment_currency_code',
            field=models.CharField(blank=True, help_text='Если оплата в другой валюте (напр. KZT для России). Пусто = совпадает с валютой отображения.', max_length=3, verbose_name='Валюта оплаты'),
        ),
        migrations.AddField(
            model_name='region',
            name='payment_currency_symbol',
            field=models.CharField(blank=True, help_text='Символ валюты оплаты (напр. ₸). Пусто = совпадает.', max_length=5, verbose_name='Символ валюты оплаты'),
        ),
    ]
