# Generated by Django 5.2.5 on 2026-03-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Название')),
                ('content', models.TextField(help_text='Текст, URL или любая строка для кодирования в QR', verbose_name='Содержимое')),
                ('image', models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='QR-код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'QR-код',
                'verbose_name_plural': 'QR-коды',
                'ordering': ['-created_at'],
            },
        ),
    ]
