# Generated by Django 5.2.5 on 2026-03-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='image',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='image_lg',
            field=models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='QR большой'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='image_md',
            field=models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='QR средний'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='image_sm',
            field=models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='QR маленький'),
        ),
    ]
