# Generated by Django 5.2.5 on 2026-03-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0002_remove_qrcode_image_qrcode_image_lg_qrcode_image_md_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='image_lg',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='image_md',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='image_sm',
        ),
    ]
