# Generated by Django 5.2.5 on 2026-03-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0003_remove_qrcode_image_lg_remove_qrcode_image_md_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='preview',
            field=models.ImageField(blank=True, upload_to='qrcodes/previews/', verbose_name='Превью'),
        ),
    ]
