# Generated by Django 5.2.5 on 2026-02-27 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('abbr', models.CharField(max_length=20, verbose_name='Сокращение')),
                ('data_type', models.CharField(choices=[('text', 'Строка'), ('integer', 'Целое число'), ('decimal', 'Десятичное число')], default='text', max_length=10, verbose_name='Тип данных')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Обложка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='META Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='META Description')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='catalog_cat_slug_695af4_idx'), models.Index(fields=['is_active', 'order'], name='catalog_cat_is_acti_7b2d26_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('badge', models.CharField(blank=True, choices=[('bestseller', 'Хит продаж'), ('new', 'Новинка'), ('sale', 'Скидка')], max_length=20, verbose_name='Бейдж')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('zoom_image', models.ImageField(blank=True, upload_to='products/zoom/', verbose_name='Zoom изображение')),
                ('zoom_rotation_angle', models.IntegerField(default=15, help_text='Градус поворота для zoom-эффекта при скролле', verbose_name='Угол поворота (GSAP)')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='META Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='META Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, verbose_name='Значение')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.characteristic', verbose_name='Характеристика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товара',
                'ordering': ['characteristic__order'],
            },
        ),
        migrations.CreateModel(
            name='ProductIndividualImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/individual/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=300, verbose_name='Alt текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото индивидуальной упаковки',
                'verbose_name_plural': 'Фото индивидуальной упаковки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductMainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/main/', verbose_name='Изображение')),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to='products/thumbs/', verbose_name='Миниатюра')),
                ('alt_text', models.CharField(blank=True, max_length=300, verbose_name='Alt текст')),
                ('is_cover', models.BooleanField(default=False, help_text='Главная картинка товара (одна на товар)', verbose_name='Обложка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Основное фото',
                'verbose_name_plural': 'Основные фото',
                'ordering': ['-is_cover', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProductPackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/package/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=300, verbose_name='Alt текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото упаковки',
                'verbose_name_plural': 'Фото упаковки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: M, L, XL, 3 шт, 12 шт', max_length=50, verbose_name='Размер')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (₸)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена (₸)')),
                ('price_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (₽)')),
                ('old_price_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена (₽)')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='characteristic',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Если не указана — значение свободный текст', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.unitofmeasure', verbose_name='Единица измерения'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='catalog_pro_slug_2b1eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'category'], name='catalog_pro_is_acti_1a8de5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='catalog_pro_created_eee82f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcharacteristic',
            unique_together={('product', 'characteristic')},
        ),
        migrations.AddIndex(
            model_name='productsize',
            index=models.Index(fields=['sku'], name='catalog_pro_sku_10f6ed_idx'),
        ),
    ]
