# Generated by Django 5.2.5 on 2026-02-28 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_sitesettings'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='regions.region', verbose_name='Регион')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_prices', to='catalog.productsize', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Цена региона',
                'verbose_name_plural': 'Цены регионов',
                'indexes': [models.Index(fields=['size', 'region'], name='catalog_reg_size_id_27b861_idx')],
                'unique_together': {('size', 'region')},
            },
        ),
    ]
