# Generated by Django 5.2.5 on 2026-02-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_regionprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='old_price_rub',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='price_rub',
        ),
        migrations.AlterField(
            model_name='productsize',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая базовая цена'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Fallback-цена (KZT). Региональные цены в RegionPrice.', max_digits=10, verbose_name='Базовая цена'),
        ),
    ]
