# Generated by Django 5.2.5 on 2026-02-28 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_price_rub_fields'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='in_stock',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Остаток')),
                ('reserved', models.PositiveIntegerField(default=0, help_text='Зарезервировано в неоплаченных заказах', verbose_name='Зарезервировано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='regions.region', verbose_name='Регион')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.productsize', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
                'indexes': [models.Index(fields=['size', 'region'], name='catalog_sto_size_id_da8229_idx')],
                'unique_together': {('size', 'region')},
            },
        ),
    ]
