# Generated by Django 5.2.5 on 2026-02-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_stock_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tagline',
            field=models.CharField(blank=True, help_text='Уникальное торговое предложение. Выводится вместо названия на сайте.', max_length=500, verbose_name='УТП'),
        ),
    ]
