# Generated by Django 5.2.5 on 2026-02-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_add_product_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='META Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='META Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='META Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_kk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='name_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_kk',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_kk',
            field=models.CharField(max_length=500, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='META Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='META Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='META Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_kk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_kk',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='tagline_en',
            field=models.CharField(blank=True, help_text='Уникальное торговое предложение. Выводится вместо названия на сайте.', max_length=500, null=True, verbose_name='УТП'),
        ),
        migrations.AddField(
            model_name='product',
            name='tagline_kk',
            field=models.CharField(blank=True, help_text='Уникальное торговое предложение. Выводится вместо названия на сайте.', max_length=500, null=True, verbose_name='УТП'),
        ),
        migrations.AddField(
            model_name='product',
            name='tagline_ru',
            field=models.CharField(blank=True, help_text='Уникальное торговое предложение. Выводится вместо названия на сайте.', max_length=500, null=True, verbose_name='УТП'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
