# Generated by Django 5.2.5 on 2026-03-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_category_description_en_category_description_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='transparent_image',
            field=models.ImageField(blank=True, help_text='PNG с прозрачным фоном. Для результатов квиза и промо.', upload_to='products/transparent/', verbose_name='Прозрачное фото (PNG)'),
        ),
    ]
