# Generated by Django 5.2.5 on 2026-03-04 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_add_transparent_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_important', models.CharField(blank=True, choices=[('texture', 'Текстура'), ('aroma', 'Аромат'), ('feel', 'Неощутимость')], max_length=20, verbose_name='Q1: Что важнее?')),
                ('q2_aroma', models.CharField(blank=True, choices=[('banana', 'Банан'), ('strawberry', 'Клубника'), ('chocolate', 'Шоколад')], max_length=20, verbose_name='Q2: Аромат')),
                ('q3_frequency', models.CharField(blank=True, choices=[('daily', 'Каждый день'), ('weekly', 'Несколько раз в неделю'), ('monthly', 'Несколько раз в месяц'), ('yearly', 'Редко')], max_length=20, verbose_name='Q3: Частота')),
                ('q4_lube', models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет')], max_length=10, verbose_name='Q4: Доп. смазка?')),
                ('priority', models.IntegerField(default=0, help_text='Чем выше — тем приоритетнее. При совпадении нескольких правил побеждает с высшим.', verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_rules', to='catalog.product', verbose_name='Рекомендуемый товар')),
            ],
            options={
                'verbose_name': 'Правило квиза',
                'verbose_name_plural': 'Правила квиза',
                'ordering': ['-priority'],
            },
        ),
    ]
