# Generated by Django 5.2.5 on 2026-03-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_quizrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Количество штук в упаковке (5, 17, 30). Для подбора размера пачки в квизе.', null=True, verbose_name='Кол-во в пачке'),
        ),
    ]
