# Generated by Django 5.2.5 on 2026-03-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_pack_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcharacteristic',
            name='value_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='value_kk',
            field=models.CharField(max_length=500, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='value_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='quizrule',
            name='q2_aroma',
            field=models.CharField(blank=True, choices=[('banana', 'Банан'), ('strawberry', 'Клубника'), ('chocolate', 'Шоколад'), ('none', 'Без аромата')], max_length=20, verbose_name='Q2: Аромат'),
        ),
    ]
