# Generated by Django 5.2.5 on 2026-03-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_productcharacteristic_value_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcharacteristic',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='Вспомогательный текст под значением (опционально)', max_length=500, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='subtitle_en',
            field=models.CharField(blank=True, default='', help_text='Вспомогательный текст под значением (опционально)', max_length=500, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='subtitle_kk',
            field=models.CharField(blank=True, default='', help_text='Вспомогательный текст под значением (опционально)', max_length=500, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='subtitle_ru',
            field=models.CharField(blank=True, default='', help_text='Вспомогательный текст под значением (опционально)', max_length=500, null=True, verbose_name='Подпись'),
        ),
    ]
