# Generated by Django 5.2.5 on 2026-03-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_productcharacteristic_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmainimage',
            name='image_kk',
            field=models.ImageField(blank=True, help_text='Фото пачки на казахском. Если пусто — используется основное.', upload_to='products/main/kk/', verbose_name='Изображение (KK)'),
        ),
        migrations.AddField(
            model_name='productmainimage',
            name='thumbnail_kk',
            field=models.ImageField(blank=True, editable=False, upload_to='products/thumbs/kk/', verbose_name='Миниатюра (KK)'),
        ),
        migrations.AlterField(
            model_name='productmainimage',
            name='image',
            field=models.ImageField(upload_to='products/main/', verbose_name='Изображение (RU)'),
        ),
    ]
