# Generated by Django 5.2.5 on 2026-03-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_main_image_kk'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='transparent_image_kk',
            field=models.ImageField(blank=True, help_text='Казахская версия. Если пусто — используется основное.', upload_to='products/transparent/kk/', verbose_name='Прозрачное фото KK (PNG)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='transparent_image',
            field=models.ImageField(blank=True, help_text='PNG с прозрачным фоном. Для результатов квиза и промо.', upload_to='products/transparent/', verbose_name='Прозрачное фото RU (PNG)'),
        ),
    ]
