# Generated by Django 5.2.5 on 2026-03-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_transparent_image_kk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pack_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Количество штук в упаковке (5, 17, 30, 34 и т.д.).', null=True, verbose_name='Кол-во в упаковке'),
        ),
        # Удаляем QuizRule только из state каталога, таблицу НЕ трогаем
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='QuizRule',
                ),
            ],
            database_operations=[],
        ),
    ]
