# Generated by Django 5.2.5 on 2026-03-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_product_pack_quantity_delete_quizrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='productindividualimage',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Alt текст'),
        ),
        migrations.AddField(
            model_name='productindividualimage',
            name='alt_text_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Alt текст'),
        ),
        migrations.AddField(
            model_name='productindividualimage',
            name='alt_text_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Alt текст'),
        ),
        migrations.AddField(
            model_name='productmainimage',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Alt текст'),
        ),
        migrations.AddField(
            model_name='productmainimage',
            name='alt_text_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Alt текст'),
        ),
        migrations.AddField(
            model_name='productmainimage',
            name='alt_text_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Alt текст'),
        ),
        migrations.AddField(
            model_name='productpackageimage',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Alt текст'),
        ),
        migrations.AddField(
            model_name='productpackageimage',
            name='alt_text_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Alt текст'),
        ),
        migrations.AddField(
            model_name='productpackageimage',
            name='alt_text_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Alt текст'),
        ),
    ]
