# Generated by Django 5.2.5 on 2026-05-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_image_alt_text_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='coming_soon',
            field=models.BooleanField(default=False, help_text='Размер ещё не доступен. Покупка отключена, цена скрыта.', verbose_name='Скоро в продаже'),
        ),
    ]
