# Generated by Django 5.2.5 on 2026-07-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_productsize_coming_soon'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_slug_2b1eb6_idx',
        ),
        migrations.RemoveIndex(
            model_name='regionprice',
            name='catalog_reg_size_id_27b861_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='catalog_sto_size_id_da8229_idx',
        ),
    ]
