# Generated by Django 5.2.16 on 2026-07-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_remove_product_catalog_pro_slug_2b1eb6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='transparent_image_2x',
            field=models.ImageField(blank=True, editable=False, upload_to='products/transparent/2x/', verbose_name='Прозрачное фото RU 2x (ретина)'),
        ),
        migrations.AddField(
            model_name='product',
            name='transparent_image_kk_2x',
            field=models.ImageField(blank=True, editable=False, upload_to='products/transparent/kk/2x/', verbose_name='Прозрачное фото KK 2x (ретина)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='transparent_image',
            field=models.ImageField(blank=True, help_text='PNG с прозрачным фоном, обрезка вплотную к пачке. Любой размер: система сама нарежет стандарт (до 400px) и ретину (до 800px).', upload_to='products/transparent/', verbose_name='Прозрачное фото RU (PNG)'),
        ),
    ]
