# Generated by Django 5.2.16 on 2026-07-31 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_product_transparent_image_2x_and_more'),
        ('modals', '0003_interactivemodal_modalstep_delete_partnerrequest_and_more'),
        ('pages', '0021_offlinestore'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='contraindications_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.page', verbose_name='Страница «Противопоказания»'),
        ),
        migrations.AddField(
            model_name='category',
            name='size_guide_modal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='modals.interactivemodal', verbose_name='Модалка «Как выбрать размер»'),
        ),
        migrations.AddField(
            model_name='category',
            name='size_guide_page',
            field=models.ForeignKey(blank=True, help_text='Открывается по ссылке, если модалка не выбрана', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.page', verbose_name='Страница «Как выбрать размер»'),
        ),
        migrations.AddField(
            model_name='category',
            name='usage_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.page', verbose_name='Страница «Инструкция по применению»'),
        ),
    ]
