# Generated by Django 5.2.5 on 2026-02-28 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_stock_model'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён'), ('expired', 'Истёк')], default='pending', max_length=20, verbose_name='Статус')),
                ('customer_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('payment_id', models.CharField(blank=True, help_text='ID транзакции от эквайринга', max_length=200, verbose_name='ID платежа')),
                ('payment_url', models.URLField(blank=True, verbose_name='Ссылка на оплату')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа')),
                ('expires_at', models.DateTimeField(help_text='Срок действия счёта на оплату', verbose_name='Истекает')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='regions.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300, verbose_name='Название товара')),
                ('size_name', models.CharField(max_length=50, verbose_name='Размер')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ед.')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productsize', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'expires_at'], name='orders_orde_status_62907b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['number'], name='orders_orde_number_539d36_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='orders_orde_created_f0ce29_idx'),
        ),
    ]
