# Generated by Django 5.2.5 on 2026-03-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_gateway',
            field=models.CharField(blank=True, help_text='Код шлюза: vtb, halyk', max_length=20, verbose_name='Шлюз'),
        ),
    ]
