# Generated by Django 5.2.5 on 2026-03-03 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_payment_gateway'),
        ('regions', '0003_payment_gateway'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_id'], name='orders_orde_payment_59dc0b_idx'),
        ),
    ]
