# Generated by Django 5.2.5 on 2026-03-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cart_favorite_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='display_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сумма в валюте отображения (напр. RUB), если отличается от валюты оплаты', max_digits=10, null=True, verbose_name='Сумма отображения'),
        ),
        migrations.AddField(
            model_name='order',
            name='display_currency_code',
            field=models.CharField(blank=True, help_text='Код валюты отображения (напр. RUB)', max_length=3, verbose_name='Валюта отображения'),
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Курс конвертации: 1 единица display_currency = X KZT', max_digits=12, null=True, verbose_name='Курс на момент заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='В валюте оплаты (KZT если конвертация)', max_digits=10, verbose_name='Сумма заказа'),
        ),
    ]
