# Generated by Django 5.2.5 on 2026-03-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_display_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254, verbose_name='Получатель')),
                ('template_slug', models.CharField(max_length=100, verbose_name='Шаблон')),
                ('subject', models.CharField(max_length=300, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Текст')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('retry', 'Ожидает повтора'), ('failed', 'Ошибка')], default='sent', max_length=10, verbose_name='Статус')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='Повторить после')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен')),
            ],
            options={
                'verbose_name': 'Лог email',
                'verbose_name_plural': 'Логи email',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='orders_emai_status_5626e6_idx')],
            },
        ),
    ]
