# Generated by Django 5.2.16 on 2026-07-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_status_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Срок действия счёта на оплату. Пусто — заказ без онлайн-оплаты, обрабатывается менеджером и не истекает', null=True, verbose_name='Истекает'),
        ),
    ]
