# Generated by Django 5.2.16 on 2026-08-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expired_paid_alerted_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Когда владельцу ушёл алерт о деньгах по истёкшему заказу (крон check_expired_paid). Пусто — алерта не было', null=True, verbose_name='Алерт «истёк, но оплачен»'),
        ),
    ]
