# Generated by Django 5.2.5 on 2026-03-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, help_text='Путь без домена, например: /100-sex-positions/', max_length=500, unique=True, verbose_name='Путь на сайте')),
                ('destination', models.CharField(help_text='Полный URL, например: https://old-site.com/100-sex-positions#popup:myform', max_length=500, verbose_name='Куда перенаправлять')),
                ('redirect_type', models.IntegerField(choices=[(301, '301 — Постоянный'), (302, '302 — Временный')], default=302, verbose_name='Тип редиректа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Редирект',
                'verbose_name_plural': 'Редиректы',
                'ordering': ['path'],
                'indexes': [models.Index(fields=['is_active', 'path'], name='redirects_r_is_acti_f3febf_idx')],
            },
        ),
    ]
